---
title: "Instacart Information Dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(p8105.datasets)

library(plotly)
library(htmlwidgets)
```

```{r include=FALSE}
data("instacart")
head(instacart, 5)
```


Column {data-width=550}
-----------------------------------------------------------------------

### Bubble Plot

```{r}
instacart %>% 
 filter(
   department == "household", 
   order_hour_of_day %in% 12:18
  ) %>% 
  group_by(order_hour_of_day) %>% 
  count(aisle) %>% 
  plot_ly(
    x = ~aisle, y = ~order_hour_of_day, color = ~aisle, type = "scatter", mode = "markers", marker = list(size = ~n/15, opacity = 0.5))


```

Column {data-width=450}
-----------------------------------------------------------------------

### Box Plot

```{r}
instacart %>% 
  filter(
    days_since_prior_order %in% 1:29, 
    department == "household"
    ) %>% 
  select(days_since_prior_order, aisle) %>% 
  mutate(
    days_since_prior_order = as.numeric(days_since_prior_order),
    aisle = fct_reorder(aisle, days_since_prior_order)) %>% 
  plot_ly(
    x = ~aisle, y = ~days_since_prior_order, color = ~aisle, type = "box", 
    colors = "viridis"
  )
```

### Bar Plot

```{r}
instacart %>% 
  filter(
    aisle == "spirits"
  ) %>% 
  group_by(order_hour_of_day) %>% 
	count(aisle) %>% 
  mutate(
    order_hour_of_day = as_factor(order_hour_of_day), 
    text_label = str_c("Order Number: ", n)) %>% 
  plot_ly(
    x = ~order_hour_of_day, y = ~n, color = ~order_hour_of_day, type = "bar", 
    colors = "viridis",  text = ~text_label, alpha = 0.8
  )
```

